FROM nginx:1.27-alpine

COPY index.html /usr/share/nginx/html/
COPY jenn-pic.jpeg /usr/share/nginx/html/
COPY Jennifer_Yavuz_Design_Portfolio.pdf /usr/share/nginx/html/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
